// PDF Generation utility for Luna
import { LunaPlan } from '../types';

export async function generatePlanPDF(plan: LunaPlan, privacyMode: string): Promise<Blob> {
  // Create HTML content for PDF
  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
      padding-bottom: 20px;
      border-bottom: 3px solid #8b5cf6;
    }
    .logo {
      font-size: 48px;
      margin-bottom: 10px;
    }
    .title {
      font-size: 28px;
      font-weight: bold;
      color: #8b5cf6;
      margin-bottom: 10px;
    }
    .subtitle {
      font-size: 14px;
      color: #6b7280;
    }
    .section {
      margin-bottom: 30px;
    }
    .section-title {
      font-size: 20px;
      font-weight: bold;
      color: #8b5cf6;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e5e7eb;
    }
    .summary {
      background: #f3f4f6;
      padding: 20px;
      border-radius: 8px;
      margin-bottom: 20px;
      border-left: 4px solid #8b5cf6;
    }
    .insights {
      list-style: none;
      padding: 0;
    }
    .insight-item {
      padding: 12px;
      margin-bottom: 10px;
      background: #faf5ff;
      border-radius: 6px;
      padding-left: 40px;
      position: relative;
    }
    .insight-item:before {
      content: "✓";
      position: absolute;
      left: 15px;
      color: #8b5cf6;
      font-weight: bold;
      font-size: 18px;
    }
    .next-steps {
      counter-reset: step-counter;
    }
    .step {
      margin-bottom: 20px;
      padding: 20px;
      background: #ffffff;
      border: 2px solid #e5e7eb;
      border-radius: 8px;
      counter-increment: step-counter;
      position: relative;
      padding-left: 60px;
    }
    .step:before {
      content: counter(step-counter);
      position: absolute;
      left: 20px;
      top: 20px;
      background: #8b5cf6;
      color: white;
      width: 30px;
      height: 30px;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: bold;
    }
    .step-title {
      font-size: 16px;
      font-weight: bold;
      color: #1f2937;
      margin-bottom: 8px;
    }
    .step-description {
      font-size: 14px;
      color: #4b5563;
      line-height: 1.6;
    }
    .metadata {
      margin-top: 40px;
      padding: 20px;
      background: #f9fafb;
      border-radius: 8px;
      font-size: 12px;
      color: #6b7280;
    }
    .metadata-row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 8px;
    }
    .metadata-label {
      font-weight: bold;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      font-size: 12px;
      color: #9ca3af;
    }
    .cta-box {
      margin-top: 30px;
      padding: 25px;
      background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
      color: white;
      border-radius: 12px;
      text-align: center;
    }
    .cta-title {
      font-size: 18px;
      font-weight: bold;
      margin-bottom: 10px;
    }
    .cta-text {
      font-size: 14px;
      margin-bottom: 15px;
      opacity: 0.95;
    }
    .cta-link {
      display: inline-block;
      background: white;
      color: #8b5cf6;
      padding: 12px 30px;
      border-radius: 8px;
      text-decoration: none;
      font-weight: bold;
      font-size: 14px;
    }
    @media print {
      body {
        padding: 20px;
      }
      .cta-box {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="logo">🌕</div>
    <div class="title">Your Personalized Action Plan</div>
    <div class="subtitle">Generated by Luna AI Assistant • Surim Studio</div>
  </div>

  <div class="section">
    <div class="section-title">Project Summary</div>
    <div class="summary">
      ${plan.summary}
    </div>
  </div>

  <div class="section">
    <div class="section-title">Key Insights</div>
    <ul class="insights">
      ${plan.keyInsights.map(insight => `
        <li class="insight-item">${insight}</li>
      `).join('')}
    </ul>
  </div>

  <div class="section">
    <div class="section-title">Your Next Steps</div>
    <div class="next-steps">
      ${plan.nextSteps.map(step => `
        <div class="step">
          <div class="step-title">${step.title}</div>
          <div class="step-description">${step.description}</div>
        </div>
      `).join('')}
    </div>
  </div>

  <div class="cta-box">
    <div class="cta-title">Ready to Get Started?</div>
    <div class="cta-text">${plan.calendlyPurpose}</div>
    <a href="https://calendly.com/hello-surim/30min" class="cta-link">Book Your Free Consultation</a>
  </div>

  <div class="metadata">
    <div class="metadata-row">
      <span class="metadata-label">Estimated Scope:</span>
      <span>${plan.estimatedScope}</span>
    </div>
    <div class="metadata-row">
      <span class="metadata-label">Privacy Mode:</span>
      <span>${privacyMode === 'on-the-record' ? 'On-the-Record' : 'Confidential'}</span>
    </div>
    <div class="metadata-row">
      <span class="metadata-label">Generated:</span>
      <span>${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
    </div>
    ${plan.tags.length > 0 ? `
    <div class="metadata-row">
      <span class="metadata-label">Project Tags:</span>
      <span>${plan.tags.join(', ')}</span>
    </div>
    ` : ''}
  </div>

  <div class="footer">
    <p>Surim Studio • Digital Solutions That Transform</p>
    <p>www.surim.io • hello@surim.io</p>
  </div>
</body>
</html>
  `;

  // Convert HTML to PDF using browser print API
  return new Promise((resolve, reject) => {
    try {
      // Create a temporary iframe
      const iframe = document.createElement('iframe');
      iframe.style.display = 'none';
      document.body.appendChild(iframe);

      const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
      if (!iframeDoc) {
        throw new Error('Could not access iframe document');
      }

      iframeDoc.open();
      iframeDoc.write(htmlContent);
      iframeDoc.close();

      // Wait for content to load
      iframe.onload = () => {
        try {
          iframe.contentWindow?.print();
          
          // Clean up
          setTimeout(() => {
            document.body.removeChild(iframe);
          }, 1000);

          // Create a simple blob for download
          const blob = new Blob([htmlContent], { type: 'text/html' });
          resolve(blob);
        } catch (error) {
          reject(error);
        }
      };
    } catch (error) {
      reject(error);
    }
  });
}

export function downloadPDF(blob: Blob, filename: string = 'luna-action-plan.html') {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
