export {
  initGA,
  trackPageView,
  trackEvent,
  trackFormSubmission,
  trackButtonClick,
  trackNavigation,
  trackScrollDepth,
  trackDownload,
  trackVideoInteraction,
  trackSearch,
  trackContactForm,
  pageview,
  event,
  isGAReady,
} from "@surim/lib/gtag";
