// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  Expertiseareas: dynamic(() => import("./Expertiseareas")),
  Faq: dynamic(() => import("./Faq")),
  Imageandtext: dynamic(() => import("./Imageandtext")),
  Process: dynamic(() => import("./Process")),
  ProjectShowcase: dynamic(() => import("./ProjectShowcase")),
  ServiceGrid: dynamic(() => import("./ServiceGrid")),
  author_info: dynamic(() => import("./AuthorInfo")),
  blog_article_card: dynamic(() => import("./BlogArticleCard")),
  blog_list: dynamic(() => import("./BlogList")),
  breadcrumbs: dynamic(() => import("./Breadcrumbs")),
  case_study_text_panel: dynamic(() => import("./CaseStudyTextPanel")),
  collectibles: dynamic(() => import("./Collectibles")),
  compact_hero: dynamic(() => import("./CompactHero")),
  contact: dynamic(() => import("./Contact")),
  eventbrite: dynamic(() => import("./Eventbrite")),
  footer: dynamic(() => import("./Footer")),
  global_community: dynamic(() => import("./GlobalCommunity")),
  hero: dynamic(() => import("./Hero")),
  navigation_menu: dynamic(() => import("./NavigationMenu")),
  our_team: dynamic(() => import("./OurTeam")),
  parallax_line: dynamic(() => import("./ParallaxLine")),
  parallax_text_image: dynamic(() => import("./ParallaxTextImage")),
  privacy_text_box: dynamic(() => import("./PrivacyTextBox")),
  transmedia_hero: dynamic(() => import("./TransmediaHero")),
  virtual_team_circle: dynamic(() => import("./VirtualTeamCircle")),
};
